# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text2',
        ),
    ]
